name: build ts into js
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: write
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_CONTENT_W }}
    - name: install node v18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: yarn install
      run: yarn install
    - name: ts compile
      run: yarn build
    - name: useful files copy
      run: |
        cp -r .github/ build/
        mkdir build/root/
        cp package.json build/
        cp yarn.lock build/
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.PAT_CONTENT_W }}
        MESSAGE: "Build: ({sha}) {msg}"